const API_BASE_URL = 'http://localhost:8080/api/';
const BUILDING_CONTROLLER = `${API_BASE_URL}building/`;
const COMPLAINT_CONTROLLER = `${API_BASE_URL}complaint/`;
const FILE_CONTROLLER = `${API_BASE_URL}file/`;
const IMAGE_CONTROLLER = `${API_BASE_URL}image/`;
const PERSON_CONTROLLER = `${API_BASE_URL}person/`;
const AUTH_CONTROLLER = `${API_BASE_URL}auth/`;

const GET_BUILDING_WITH_UNITS_BY_TENANT_ID = `${BUILDING_CONTROLLER}buildings/tenant/`;
const GET_COMPLAINTS_BY_TENANT_OR_ADMIN = `${COMPLAINT_CONTROLLER}complaints/tenant/`;
const UPDATE_COMPLAINT_STATUS = `${COMPLAINT_CONTROLLER}updateComplaintStatus`;
const REGISTER = `${AUTH_CONTROLLER}authenticate`;
const LOGIN = `${AUTH_CONTROLLER}login`

export {
    REGISTER,
    PERSON_CONTROLLER,
    BUILDING_CONTROLLER,
    COMPLAINT_CONTROLLER,
    UPDATE_COMPLAINT_STATUS,
    GET_BUILDING_WITH_UNITS_BY_TENANT_ID,
    GET_COMPLAINTS_BY_TENANT_OR_ADMIN,
    FILE_CONTROLLER,
    IMAGE_CONTROLLER,
    AUTH_CONTROLLER,
    LOGIN
}
